In [1]:
import json
import os
from hta.trace_analysis import TraceAnalysis

In [2]:

def add_rank_to_trace(filepath, rank):
    with open(filepath) as f:
        data = json.load(f)

    data["distributedInfo"] = {"rank": rank}

    with open(filepath, "w") as f:
        json.dump(data, f)

In [3]:
analyzer = TraceAnalysis(trace_dir = "traces_2")

Parsed traces_2/sigma-3_2611403.1763927675644775313.pt.trace.json.gz time = 0.94 seconds
Parsed traces_2/sigma-3_2611404.1763927675649759538.pt.trace.json.gz time = 0.95 seconds
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Rounding down ns resolution events due to issue with events overlapping. ts dtype = float64, dur dtype = float64.Please see https://github.com/pytorch/pytorch/pull/122425
Parsed traces_2/sigma-3_2611403.1763927675644775313.pt.trace.json.gz backend=ParserBackend.JSON in 2.61 seconds; current PID:87390
Parsed traces_2/sigma-3_2611404.1763927675649759538.pt.trace.json.gz backend=ParserBackend.JSON in 2.62 seconds; current PID:87389
Overall parsing of traces_2/sigma-3_2611403.1763927675644775313.pt.trace.json.gz in 2.96 seconds; current PID:87390
Overall parsing of traces_2/sigma-3_2611404.1763927675649759538.pt.trace.json.gz in 2.98 seconds; current PID:87389
leaving parse_multiple_ranks duration=3.53 seconds
leaving parse_traces duration=3.53 seconds

In [4]:
time_spent_df = analyzer.get_temporal_breakdown()
time_spent_df

,rank,idle_time(us),compute_time(us),non_compute_time(us),kernel_time(us),idle_time_pctg,compute_time_pctg,non_compute_time_pctg
0,0,49206.0,331928.0,8889.0,390023.0,12.62,85.10,2.28
1,1,53183.0,332136.0,5820.0,391139.0,13.60,84.92,1.49

In [5]:
idle_time_df = analyzer.get_idle_time_breakdown()
idle_time_df

(   rank stream idle_category  idle_time  idle_time_ratio
 0     0      7     host_wait    49927.0             0.89
 1     0      7   kernel_wait     5025.0             0.09
 2     0      7         other     1168.0             0.02
 3     0     41     host_wait   155851.0             1.00
 4     0     41         other      716.0             0.00
 5     0     33   kernel_wait        6.0             0.00
 6     0     33         other   159069.0             1.00
 7     0     49     host_wait     1526.0             0.61
 8     0     49   kernel_wait      262.0             0.10
 9     0     49         other      724.0             0.29,
 None)

In [13]:
kernel_type_metrics_df, kernel_metrics_df = analyzer.get_gpu_kernel_breakdown()
#kernel_type_metrics_df
kernel_metrics_df

/Users/jacob/miniconda3/lib/python3.11/site-packages/hta/analyzers/breakdown_analysis.py:517: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/Users/jacob/miniconda3/lib/python3.11/site-packages/hta/analyzers/breakdown_analysis.py:517: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/Users/jacob/miniconda3/lib/python3.11/site-packages/hta/analyzers/breakdown_analysis.py:517: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/Users/jacob/miniconda3/lib/python3.11/site-packages/hta/analyzers/breakdown_analysis.py:517: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/Users/jacob/miniconda3/lib/python3.11/site-packages/hta/analyzers/breakdown_analysis.py:517: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/Users/jacob/miniconda3/lib/python3.11/site-packages/hta/analyzers/breakdown_analysis.py:517: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

,name,sum (us),max (us),min (us),stddev,mean (us),kernel_type,rank
0,ncclDevKernel_AllGather_RING_LL(ncclDevKernelA...,19376.0,1463.0,53.0,600.266095,745.230769,COMMUNICATION,0
1,ncclDevKernel_AllGather_RING_LL(ncclDevKernelA...,3051.0,324.0,43.0,75.949953,117.346154,COMMUNICATION,1
2,ampere_bf16_s1688gemm_bf16_128x128_ldg8_f2f_st...,10993.0,10993.0,10993.0,0.000000,10993.000000,COMPUTATION,0
3,ampere_bf16_s1688gemm_bf16_128x128_ldg8_f2f_st...,11016.0,11016.0,11016.0,0.000000,11016.000000,COMPUTATION,1
4,others,156716.0,9519.0,0.0,2218.316901,1536.431373,COMPUTATION,0
5,others,156953.0,9646.0,0.0,2229.497903,1538.754902,COMPUTATION,1
6,void (anonymous namespace)::softmax_warp_backw...,20018.0,20018.0,20018.0,0.000000,20018.000000,COMPUTATION,0
7,void (anonymous namespace)::softmax_warp_backw...,20019.0,20019.0,20019.0,0.000000,20019.000000,COMPUTATION,1
8,void (anonymous namespace)::softmax_warp_forwa...,13502.0,13502.0,13502.0,0.000000,13502.000000,COMPUTATION,0
9,void (anonymous namespace)::softmax_warp_forwa...,13434.0,13434.0,13434.0,0.000000,13434.000000,COMPUTATION,1
10,void at::native::(anonymous namespace)::fused_...,13760.0,13760.0,13760.0,0.000000,13760.000000,COMPUTATION,0
11,void at::native::(anonymous namespace)::fused_...,13782.0,13782.0,13782.0,0.000000,13782.000000,COMPUTATION,1
12,"void at::native::elementwise_kernel<128, 4, at...",10968.0,10968.0,10968.0,0.000000,10968.000000,COMPUTATION,0
13,"void at::native::elementwise_kernel<128, 4, at...",10993.0,10993.0,10993.0,0.000000,10993.000000,COMPUTATION,1
14,void at::native::unrolled_elementwise_kernel<a...,26116.0,26116.0,26116.0,0.000000,26116.000000,COMPUTATION,0
15,void at::native::unrolled_elementwise_kernel<a...,26077.0,26077.0,26077.0,0.000000,26077.000000,COMPUTATION,1
16,void at::native::vectorized_elementwise_kernel...,24565.0,24565.0,24565.0,0.000000,24565.000000,COMPUTATION,0
17,void at::native::vectorized_elementwise_kernel...,24576.0,24576.0,24576.0,0.000000,24576.000000,COMPUTATION,1
18,void at::native::vectorized_elementwise_kernel...,13257.0,13257.0,13257.0,0.000000,13257.000000,COMPUTATION,0
19,void at::native::vectorized_elementwise_kernel...,13249.0,13249.0,13249.0,0.000000,13249.000000,COMPUTATION,1
20,void at::native::vectorized_elementwise_kernel...,14680.0,14680.0,14680.0,0.000000,14680.000000,COMPUTATION,0
21,void at::native::vectorized_elementwise_kernel...,14659.0,14659.0,14659.0,0.000000,14659.000000,COMPUTATION,1
22,void at::native::vectorized_elementwise_kernel...,29047.0,29047.0,29047.0,0.000000,29047.000000,COMPUTATION,0
23,void at::native::vectorized_elementwise_kernel...,28833.0,28833.0,28833.0,0.000000,28833.000000,COMPUTATION,1
24,Memcpy DtoD (Device -> Device),5433.0,186.0,1.0,43.740079,50.775701,MEMORY,0
25,Memcpy DtoD (Device -> Device),4997.0,185.0,1.0,46.652512,46.700935,MEMORY,1
26,Memcpy DtoH (Device -> Pinned),0.0,1.0,-1.0,0.516398,0.000000,MEMORY,0
27,Memcpy DtoH (Device -> Pinned),4.0,2.0,0.0,0.577350,0.250000,MEMORY,1
28,Memcpy HtoD (Pageable -> Device),18.0,7.0,5.0,1.000000,6.000000,MEMORY,0
29,Memcpy HtoD (Pageable -> Device),20.0,7.0,6.0,0.577350,6.666667,MEMORY,1
30,Memset (Device),-8.0,2.0,-1.0,0.550042,-0.081633,MEMORY,0
31,Memset (Device),-2.0,3.0,-1.0,0.641834,-0.020408,MEMORY,1

In [14]:
overlap_df = analyzer.get_comm_comp_overlap()
overlap_df

/Users/jacob/miniconda3/lib/python3.11/site-packages/hta/analyzers/communication_analysis.py:56: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/Users/jacob/miniconda3/lib/python3.11/site-packages/hta/analyzers/communication_analysis.py:59: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/Users/jacob/miniconda3/lib/python3.11/site-packages/hta/analyzers/communication_analysis.py:56: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/Users/jacob/miniconda3/lib/python3.11/site-packages/hta/analyzers/communication_analysis.py:59: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

   rank  comp_comm_overlap_pctg
0     0                   74.82
1     1                   40.38